SOURCE_ROUTING = {
    "Cricket": ["reuters.com","apnews.com","icc-cricket.com","bcci.tv","wisden.com","espncricinfo.com","skysports.com"],
    "Football": ["fifa.com","uefa.com","the-aiff.com","reuters.com","apnews.com","bbc.com","transfermarkt.com"],
    "Other Sports": ["bwfbadminton.com","prokabaddi.com","fih.ch","hockeyindia.org","worldathletics.org","fide.com","uww.org","olympics.com","thebridge.in","reuters.com"],
    "Indian National Politics": ["pib.gov.in","sansad.in","eci.gov.in","reuters.com","apnews.com","indianexpress.com","thehindu.com","thewire.in"],
    "State Politics": ["eci.gov.in","indianexpress.com","thehindu.com","manoramaonline.com","nenow.in","reuters.com"],
    "International Politics": ["reuters.com","apnews.com","bbc.com","thehindu.com","aljazeera.com"],
    "Elections": ["eci.gov.in","results.eci.gov.in","reuters.com","apnews.com","thehindu.com","indianexpress.com","adrindia.org"],
    "Bollywood": ["imdb.com","boxofficeindia.com","filmfare.com","screen.in","reuters.com"],
    "South Cinema": ["imdb.com","boxofficeindia.com","behindwoods.com","screen.in","reuters.com"],
    "Music": ["billboard.com","grammy.com","filmfare.com","reuters.com","rollingstone.com","thehindu.com"],
    "Ott & Web Series": ["imdb.com","ormaxmedia.com","variety.com","reuters.com","apnews.com"],
    "Health & Medicine": ["who.int","mohfw.gov.in","icmr.gov.in","cdc.gov","pubmed.ncbi.nlm.nih.gov","bmj.com","thelancet.com","reuters.com","apnews.com"],
    "Covid & Epidemics": ["who.int","cdc.gov","mohfw.gov.in","icmr.gov.in","worldometers.info","reuters.com","apnews.com"],
    "Science & Space": ["isro.gov.in","nasa.gov","nature.com","sciencenews.org","space.com","reuters.com","apnews.com"],
    "Environment & Climate": ["ipcc.ch","unep.org","moef.gov.in","downtoearth.org.in","india.mongabay.com","reuters.com","apnews.com"],
    "Indian Economy": ["rbi.org.in","mospi.gov.in","pib.gov.in","indiabudget.gov.in","tradingeconomics.com","livemint.com","reuters.com","apnews.com"],
    "Business & Corporates": ["sebi.gov.in","rbi.org.in","reuters.com","apnews.com","livemint.com","inc42.com","businessstandard.com"],
    "Cryptocurrency & Finance": ["coingecko.com","coinmarketcap.com","sebi.gov.in","rbi.org.in","coindesk.com","reuters.com","apnews.com","cointelegraph.com"],
    "Jobs & Employment": ["mospi.gov.in","labour.gov.in","epfindia.gov.in","ilo.org","livemint.com","reuters.com","apnews.com","cmie.com"],
    "Religion & Communal": ["pib.gov.in","reuters.com","apnews.com","thehindu.com","indianexpress.com"],
    "Caste & Reservation": ["pib.gov.in","sansad.in","sci.gov.in","reuters.com","thehindu.com","indianexpress.com"],
    "Viral Social Media Claims": ["boomlive.in","altnews.in","factchecker.in","vishvasnews.com","reuters.com","apnews.com"],
    "Gender & Society": ["nhrc.nic.in","ncrb.gov.in","unwomen.org","reuters.com","thehindu.com","indianexpress.com"],
    "Ai & Technology": ["meity.gov.in","trai.gov.in","reuters.com","apnews.com","techcrunch.com","theverge.com"],
    "Cybercrime & Scams": ["cert-in.org.in","cybercrime.gov.in","reuters.com","apnews.com","thehindu.com"],
    "General": ["reuters.com","apnews.com","bbc.com","thehindu.com","indianexpress.com"]
}
